packages:
  - ./
  - playground/
patchedDependencies:
  "@nuxt/module-builder": patches/@nuxt__module-builder.patch
allowUnusedPatches: true
settings:
  cleanupUnusedCatalogs: false
  catalogMode: strict
catalog:
  "@alanscodelog/eslint-config": ^6.3.1
  "@alanscodelog/semantic-release-config": ^6.0.2
  "@alanscodelog/tsconfigs": ^6.2.0
  "@alanscodelog/utils": ^6.0.2
  "@capacitor/android": ^7.4.3
  "@capacitor/app": ^7.1.0
  "@capacitor/cli": ^7.4.3
  "@capacitor/core": ^7.4.3
  "@nuxt/eslint-config": ^1.9.0
  "@nuxt/kit": ^4.1.2
  "@nuxt/module-builder": ^1.0.2
  "@nuxt/schema": ^4.1.2
  "@nuxt/test-utils": ^3.19.2
  "@witchcraft/nuxt-logger": ^0.0.9
  "@witchcraft/nuxt-utils": ^0.3.6
  changelogen: ^0.6.2
  defu: ^6.1.4
  eslint: ^9.37.0
  husky: ^9.1.7
  nuxt: ^4.1.2
  thread-stream: ^3.1.0
  typescript: ^5.9.3
  vitest: ^3.2.4
  vue-tsc: ^3.1.0
